apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: monitoring
type: Opaque
stringData:
  PGUSER: "dbuser"
  PGPASSWORD: "dbpassword"
  PGHOST: "postgres.monitoring"
  PGPORT: "5432"
  PGDATABASE: "k8s_monitor"
  DATABASE_URL: "postgresql://dbuser:dbpassword@postgres.monitoring:5432/k8s_monitor"
  POSTGRES_USER: "dbuser"
  POSTGRES_PASSWORD: "dbpassword"
