apiVersion: v1
kind: Secret
metadata:
  name: smtp-credentials
  namespace: monitoring
type: Opaque
stringData:
  smtp_server: "smtp.example.com"
  smtp_port: "587"
  smtp_username: "alertuser@example.com"
  smtp_password: "your-smtp-password"
  email_from: "alertuser@example.com"
  email_to: "admin@example.com,ops@example.com"
